name: AA-Check-GitHub-Actions-spelling
on: # rebuild any PRs and main branch changes
  #pull_request:
  #push:
  
  # Allow you to use this workflow in another WF
  workflow_call:

jobs:
  spellcheck: # run the action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: streetsidesoftware/cspell-action@v6