name: Trivy 

on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  actions: write  # Add this line to provide necessary access

jobs:
  build:
    name: Scan IAC with Trivy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.2.2

        #Update data base (db)
      - name: Manual Trivy Setup
        uses: aquasecurity/setup-trivy@v0.2.2
        #with:
          #cache: true

      #- name: Build an image from Dockerfile
       # run: docker build -t docker.io/my-organization/my-app:$#{{ github.sha }} .

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@0.29.0
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          skip-setup-trivy: true
      
      - name: Check if SARIF file exists
        run: cat trivy-results.sarif || echo "File not found"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@main
        with:
          sarif_file: "trivy-results.sarif"
