name: Tfsec 

on:
  push:
    branches: main
  pull_request: 
    branches: main
  workflow_dispatch:

permissions:
  #contents: write
  security-events: write
  #actions: read

jobs:    
          # - name: Upload TFsec scan results to GitHub Security tab
          #   uses: github/codeql-action/upload-sarif@main
          #   with:
          #     sarif_file: ./Terraform/${{ matrix.folder }}/tfsec.sarif

    tfsec:
      name: TFsec 
      runs-on: ubuntu-latest

      steps:
        - name: Clone repo
          uses: actions/checkout@master

        - name: tfsec
          uses: aquasecurity/tfsec-action@v1.0.0
          with:
            soft_fail: true
            working_directory: .
            format: sarif
            additional_args: "--out tfsec.sarif"

        - name: See sarif file
          run: cat tfsec.sarif

        - name: Upload SARIF file
          uses: github/codeql-action/upload-sarif@v3
          with:
            # Path to SARIF file relative to the root of the repository
            sarif_file: tfsec.sarif